SainsburyWellcomeCentre/aeon_mecha

aeon/preprocess/api.py

Remove use of deprecated submodule

---

aeon/dj_pipeline/analysis/in_arena.py
aeon/dj_pipeline/ingest/create_experiment_02.py
aeon/dj_pipeline/ingest/process.py
aeon/dj_pipeline/tracking.py
aeon/dj_pipeline/webapps/sciviz/specsheet.yaml

[minor improvement in InArena calculation]
[add pipeline monitoring to sciviz]

update subject list for exp0.2

---

aeon/dj_pipeline/acquisition.py
aeon/schema/dataset.py

Related to this : #90 
Fixes the food patch device mapping error

🐛 fixed a bug in foodpatch device mapping in exp02

---

aeon/dj_pipeline/webapps/sciviz/docker-compose-local.yaml
aeon/dj_pipeline/webapps/sciviz/docker-compose-remote.yaml
aeon/dj_pipeline/webapps/sciviz/specsheet.yaml

1.  Update to the latest version of sciviz
2.  Convert Session to Visit

Sciviz update

---

aeon/dj_pipeline/populate/load_metadata.py
aeon/dj_pipeline/populate/process.py
aeon/dj_pipeline/webapps/sciviz/docker-compose-local.yaml
aeon/dj_pipeline/webapps/sciviz/specsheet.yaml

1. Updated the sci-viz with new specsheet.yaml
2. Added ingest_subject function in load_metadata.py [#156 ](https://github.com/SainsburyWellcomeCentre/aeon_mecha/issues/156). This is a draft version and will be modified to accommodate any future changes in colony.csv

sci-viz update & colony.csv ingestion

---

aeon/dj_pipeline/webapps/sciviz/README.md

Update `webapps/sciviz/README.md`

update docs for sci-viz deployment

---

aeon/dj_pipeline/tracking.py

Include only in-patch positions

---

aeon/dj_pipeline/lab.py
aeon/dj_pipeline/webapps/sciviz/specsheet.yaml

- Add `Colony` table as discussed in the meeting.
- Add `Colony` page in SciViz

Add Colony table

---

aeon/dj_pipeline/webapps/sciviz/specsheet.yaml

change the sciviz specsheet attribute name to match table definition

minor bug fix

---

aeon/dj_pipeline/utils/video.py
aeon/dj_pipeline/webapps/sciviz/docker-compose-local.yaml
aeon/dj_pipeline/webapps/sciviz/docker-compose-remote.yaml
aeon/dj_pipeline/webapps/sciviz/specsheet.yaml

- Feed `raw_data_dir` to `retrieve_video_frames` as an argument.
- Pull code from the main repo in docker-compose

Sciviz bug fix

---

aeon/dj_pipeline/utils/video.py
aeon/dj_pipeline/webapps/sciviz/docker-compose-remote.yaml
aeon/dj_pipeline/webapps/sciviz/specsheet.yaml

Improve sciviz performance & fix video reader

---

aeon/io/api.py
aeon/io/reader.py
aeon/schema/core.py

This PR fixes a number of issues and adds a few features and readers missing from the low-level API for the purposes of data QC and possibly ingestion.
Fixes #204 
Fixes #203 
Fixes #185

Fixes and improvements to the low-level API

---

aeon/dj_pipeline/populate/worker.py

import is_djtable from datajoint_utilities.dj_worker.worker_schema

fix: :bug: fix import error

---

aeon/dj_pipeline/acquisition.py
aeon/dj_pipeline/populate/worker.py
aeon/dj_pipeline/subject.py
aeon/dj_pipeline/utils/load_metadata.py

- pull from pyrat: `labid`
- check and update "availability" for each animal periodically
- deprecate the use of "colony.csv"
- added table `subject.ExperimentSubject` for the manually specification of subject and experiment association (this will be a form on SciViz)

Added `lab_id` and `available` to pyrat subjects

---

aeon/dj_pipeline/subject.py
docker/docker-compose.yml

Fix PyRat worker

---

docker/image/apt_requirements.txt

Add this dependency to `apt_requirements.txt`

build: ➕ add libtiff5 to apt_requirements.txt

---

docker/cron_script.bash

- This will create a log file in `/ceph/aeon/aeon/dj_store/logs` whenever a cron job gets run.

chore: 🔊 Create a logger for a cron job

---

aeon/dj_pipeline/analysis/block_analysis.py
aeon/dj_pipeline/utils/load_metadata.py
aeon/io/reader.py

- extract and store frame rate for each video source
- fix https://github.com/SainsburyWellcomeCentre/aeon_mecha/issues/302
- add analysis for block-subject-patch downstream from `BlockAnalysis`

add BlockSubjectPatch analysis & other minor fixes

---

aeon/dj_pipeline/acquisition.py
aeon/dj_pipeline/analysis/block_analysis.py
aeon/dj_pipeline/qc.py
aeon/dj_pipeline/streams.py
aeon/dj_pipeline/tracking.py
aeon/dj_pipeline/utils/streams_maker.py
aeon/dj_pipeline/webapps/sciviz/specsheet.yaml

feat(dj): ingest data by searching multiple directories in specified order

---

aeon/dj_pipeline/__init__.py
aeon/dj_pipeline/acquisition.py
aeon/dj_pipeline/analysis/block_analysis.py
aeon/dj_pipeline/populate/worker.py
aeon/dj_pipeline/utils/load_metadata.py

- more robust automated analysis - skip BlockAnalysis that are not 
- fix first chunk starting before epoch start
- disable automatic BlockDetection - a bit buggy and not ready to be automated, run this step manually for now
(`block_analysis.BlockDetection.populate()`)

fix first chunk starting before epoch start & disable automatic BlockDetection

---

aeon/dj_pipeline/__init__.py
aeon/dj_pipeline/analysis/block_analysis.py
aeon/dj_pipeline/tracking.py
aeon/io/reader.py

This PR includes #380 
Update ingestion to no longer require knowing the `config_file`

Update SLEAP data ingestion 

---

docs/examples/io_api_example.ipynb

Related to https://github.com/SainsburyWellcomeCentre/aeon_docs/pull/67

Mention sample data in low-level API example notebook

---

aeon/dj_pipeline/README.md
aeon/dj_pipeline/docs/PIPELINE_LOCAL_DEPLOYMENT.md
aeon/dj_pipeline/docs/notebooks/Data_Ingestion_and_Processing.ipynb
sample_dj_local_conf.json

Address https://github.com/SainsburyWellcomeCentre/aeon_docs/issues/78

Docs to deploy/onboard new datajoint pipeline for project aeon & ingest/process released data

---

aeon/dj_pipeline/analysis/block_analysis.py
aeon/dj_pipeline/scripts/update_in_patch_rfid_timestamps.py

add in_patch_rfid_timestamps in `BlockSubjectAnalysis`

---

aeon/dj_pipeline/analysis/block_analysis.py
aeon/dj_pipeline/analysis/visit.py
aeon/dj_pipeline/create_experiments/create_socialexperiment.py
aeon/dj_pipeline/subject.py
aeon/dj_pipeline/tracking.py
aeon/dj_pipeline/utils/streams_maker.py
aeon/schema/social_02.py
aeon/schema/social_03.py

This pull request introduces several updates across multiple files in the `aeon` project, with changes focusing on improving data modeling, refining logic, and updating stream handling. The most significant updates include the addition of a new `AnchorPart` class to enhance data representation, adjustments to the `make` methods for better data validation and ingestion, and updates to stream patterns for compatibility.
* Introduced a new `AnchorPart` class in `tracking.py` to represent anchor part data with fields like `x`, `y`, `likelihood`, and `timestamps`. This improves the granularity of data representation.
* Updated the `PoseIdentity` and `Part` classes in `tracking.py` to improve field descriptions and align with the new `AnchorPart` class. …

Update SLEAPTracking (new `AnchorPart` table) and Pose reader (`_222*` for SLEAP full pose + id)
